apiVersion: v1
kind: ConfigMap
metadata:
    name: global-database-config
    namespace: default
data:
  database.ini: |
    SPRING_PROFILES_ACTIVE=production-microservice
    DATABASE_URL=https://mydb.somewhere,com:3306
    