version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: /codebuild/AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: /codebuild/AWS_SECRET_ACCESS_KEY 
phases:
  install: 
    commands:
      - echo "setting up iam user credentials"
      - bash cicd/configure-named-profile.sh
      - echo "installing eksctl cli"
      - bash cicd/eksctl-install.sh
    # steps:
  pre_build:
    commands:
      - echo "creating fleetman cluster"
      - make delete-cluster
    # steps:
  build:
    commands:
      - echo build started on `date`
      # - bash orchastrator.sh