version: 0.2

# run-as: ubuntu
env:
    parameter-store:
        AWS_ACCESS_KEY_ID_PARAM: /codebuild/AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY_PARAM: 	/codebuild/AWS_SECRET_ACCESS_KEY

phases:
  install:
    on-failure: ABORT 
    commands:
      - echo "verifying secret keys $AWS_ACCESS_KEY_ID_PARAM:" $AWS_SECRET_ACCESS_KEY_PARAM
      - echo "setting up iam user credentials"
      # - bash cicd/configure-named-profile.sh
      # - echo "installing eksctl cli"
      # - bash cicd/eksctl-install.sh
    # steps:
  pre_build:
    # run-as: ubuntu
    # on-failure: ABORT 
    commands:
      - echo "creating fleetman cluster"
      # - make create-cluster
    # steps:
  build:
    commands:
      - echo build started on `date`
      # - bash orchastrator.sh