version: 0.2

# run-as: ubuntu

phases:
  install:
    on-failure: ABORT 
    commands:
      - echo "setting up iam user credentials"
      - bash cicd/configure-named-profile.sh
      - echo "installing eksctl cli"
      - bash cicd/eksctl-install.sh
    # steps:
  pre_build:
    # run-as: ubuntu
    on-failure: ABORT 
    commands:
      - echo "deleting fleetman cluster"
      - make delete-cluster
    # steps:
  # build:
  #   commands:
  #     - echo build started on `date`
  #     - bash orchastrator.sh