
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
      version: stage
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: queue
        version: stage
    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release2
        # resources:
        #   requests:
        #     memory: 160Mi
        #     cpu: 150m
        #   limits:
        #     memory: 200Mi
        #     cpu: 200m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
      version: stage
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
        version: stage
    spec:
      containers:
      - name: position-simulator
        image: richardchesterwood/k8s-fleetman-position-simulator:release2
        # resources:
        #   requests:
        #     memory: 120Mi
        #     cpu: 120m
        #   limits:
        #     memory: 150Mi
        #     cpu: 200m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
      version: stage
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: position-tracker
        version: stage
    spec:
      containers:
      - name: position-tracker
        image: richardchesterwood/k8s-fleetman-position-tracker:release2
        # resources:
        #   requests:
        #     memory: 200Mi
        #     cpu: 150m
        #   limits:
        #     memory: 250Mi
        #     cpu: 200m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
      version: stage
  replicas: 1 #3
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
        version: stage
    spec:
      containers:
      - name: api-gateway
      # performance is not greedy with memory
        image: richardchesterwood/k8s-fleetman-api-gateway:release2
        readinessProbe:
          httpGet:
            path: /
            port: 8080 
        # resources:
        #   requests:
        #     memory: 500Mi
        #     cpu: 100m
        #   limits:
        #     memory: 500Mi
        #     cpu: 200m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
      version: stage
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
        version: stage
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release2
        # resources:
        #   requests:
        #     memory: 60Mi
        #     cpu: 60m
        #   limits:
        #     memory: 150Mi
        #     cpu: 100m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice