apiVersion: v1
kind: List
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: hpa-tester
    namespace: default
  spec:
    minReplicas: 1
    maxReplicas: 4
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 150
          type: Utilization
      type: Resource
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: api-gateway

