apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-stage

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
    version: stage
  ports:
    - name: http
      port: 80
      # nodePort: 30080

  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-stage
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: queue
    version: stage
  ports:
    - name: http
      port: 8161
      # nodePort: 30010

    - name: endpoint
      port: 61616

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker-stage
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: position-tracker
    version: stage
  ports:
    - name: http
      port: 8080

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway-stage
spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: api-gateway
    version: stage
  ports:
    - name: http
      port: 8080
      # nodePort: 30020

  type: ClusterIP